### ISSUE TITLE
Possible to write to gist from a pwa?

### ISSUE THREAD

**Issue by blurymind** [jonschlinkert/gists#14]
The example heavily relies on
https://github.com/jonschlinkert/gists/blob/master/test/support/auth.js#L20
in order to work. Taking it out leads to 401 auth error from gist.

The problem is that this does not work on progressive web apps. It requires access to the user's file system as it relies on the fs module :(

My question is - any ways around this? What if I have a pwa that runs from the web browser?

**Comment by doowb** [comment]
The examples are using the `test/support/auth.js` file to create the [options](https://github.com/jonschlinkert/gists#usage) object to use when creating the instance of the `Gists` class and providing it with the GitHub authentication credentials.

The `gists` package itself does not directly use `fs` so you should be able to use this package in a web browser if you bundle it up with your other code. You'll have to authenticate with GitHub in some other way to get an access token or something, then you can use that to create the new instance of `Gists`:

```js
// Using a `Bearer` token from GitHub
// This should be retrieved using a GitHub OAuth application webflow process as described in the GitHub API documentation
const gists = new Gists({ bearer: token });
```

You can also read public gists without using authentication credentials. See the [Gists API documentation](https://developer.github.com/v3/gists/#authentication) for more information around authentication.

**Comment by blurymind** [comment]
the documentation is confusing. Is there an example out there with some pseudocode?

Does it only need the bearer key?

**Comment by blurymind** [comment]
Can this be done in a simpler way by giving it an access token?
https://github.com/settings/tokens

**Comment by blurymind** [comment]
nevermind, it was simple:just do this instead

`const gists = new Gists({ token: token });`
