### ISSUE TITLE
`create` function doesn't work

### ISSUE THREAD

**Issue by AleksueiR** [jonschlinkert/gists#5]
According to [Gist API](https://developer.github.com/v3/gists/#create-a-gist), the call to create a new gist is `POST /gists`, not `POST /gists/` as in [here](https://github.com/jonschlinkert/gists/blob/master/index.js#L187). I guess they changed it.

Thanks.

**Comment by doowb** [comment]
Thanks, looks likes #3 fixes this. I'll review it again in a little bit and get it merged in.

**Comment by doowb** [comment]
@AleksueiR this change has been published to npm as a bug fix 1.0.1
